### ISSUE TITLE
Multiple annotations for single code

### ISSUE THREAD

**Issue by hewhomustnotbenamed** [srinu-kodi/OneFramework#1]
the test flow for individual system (viz andoid, ios, web) seems redundant. Can we have multiple annotations for same scenario?

**Comment by srinu-kodi** [comment]
Will be fixed in next commits.

**Comment by srinu-kodi** [comment]
This issue has been fixed and now you can run on any type of scenario with corresponding tagging.
Here are the things that I have added as part of refactoring.
- Created the gradle task for running the tests
- Removed all the unnecessary hooks code & all the individual runners
- Updated the feature file
