### ISSUE TITLE
Request, could you please add BDD framework to existing project?

### ISSUE THREAD

**Issue by irbmfq** [srinu-kodi/OneFramework#3]
Really awesome job bro,small request could you please integrate  bdd framework to this project.hopefully it will be  useful to your followers and who wants to learn bdd with appium like  me .Thanks a lot
--Siddu

**Comment by srinu-kodi** [comment]
Thank you Rocky for your positive feedback. Infact initially I started the
framework in BDD only and later I have change it to TestNG model.

I see that is easy to add the stuff, however it involves some time for me.

Hopefully, I will add it. By the way did you use the OneFramework for your
automation.


Thanks

**Comment by srinu-kodi** [comment]
Hi Siddu,
Thank you for your positive feedback and Understand your requirement.

I see this as not an issue and it's a new type requirement. If you see this framework README also, it clearly states it is a TestNG framework. Anyhow I was planning to make this in BDD style also.

Once I block some time for this, yes I will come up with that. I will keep posting the update. 
I am closing this and you will see OneFramework-BDD soon.


Thanks
