### ISSUE TITLE
Unable to launch the test on IOS Simulator

### ISSUE THREAD

**Issue by ashishp-oyo** [srinu-kodi/OneFramework#5]
I have done the setup as mentioned in the ReadMe file. Tests are working fine on web and Android. It only fails on IOS. PFB the error logs:

[debug] [XCUITest] Xcode version set to '10.3' (tools v10.3.0.0.1.1562985497)
[debug] [XCUITest] iOS SDK Version set to '12.4'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1574946385622 (18:36:25 GMT+0530 (IST))
[debug] [XCUITest] Available devices: 
[XCUITest] Error: Unknown device or simulator UDID: '01A1C80D-7DD0-4C7E-88E6-13BBF4B4AEBA'
[XCUITest]     at XCUITestDriver.determineDevice$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:693:17)
[XCUITest]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1574946389555 (18:36:29 GMT+0530 (IST))
[debug] [W3C] Encountered internal error running command: Error: Unknown device or simulator UDID: '01A1C80D-7DD0-4C7E-88E6-13BBF4B4AEBA'
[debug] [W3C]     at XCUITestDriver.determineDevice$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:693:17)
[debug] [W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[debug] [W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[debug] [W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[debug] [W3C]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 4921 ms - 1207
[HTTP] 
TEST SKIP: testSignInOption - testing the signin page visually
TEST SKIP: testSignUpOption - testing the signup page visually
Nov 28, 2019 6:36:45 PM org.oneframework.logger.LoggingManager logMessage
INFO: Appium server has been stopped

**Comment by srinu-alef** [comment]
Hi ashishp-oyo. Log you provided clearly says that It does not recognize the device with UDID: '01A1C80D-7DD0-4C7E-88E6-13BBF4B4AEBA' and OS '12.4'.
Can you please check if you have put the device info correctly. It should work fine as long as it has correct device info...

**Comment by ashishp-oyo** [comment]
I am using the same UDID. PFB my simulator list:
bash-3.2$ appium --version
1.9.1
bash-3.2$ xcrun simctl list
== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
iPhone 6s (com.apple.CoreSimulator.SimDeviceType.iPhone-6s)
iPhone 6s Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus)
iPhone 7 (com.apple.CoreSimulator.SimDeviceType.iPhone-7)
iPhone 7 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus)
iPhone 8 (com.apple.CoreSimulator.SimDeviceType.iPhone-8)
iPhone 8 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-8-Plus)
iPhone SE (com.apple.CoreSimulator.SimDeviceType.iPhone-SE)
iPhone X (com.apple.CoreSimulator.SimDeviceType.iPhone-X)
iPhone Xs (com.apple.CoreSimulator.SimDeviceType.iPhone-XS)
iPhone Xs Max (com.apple.CoreSimulator.SimDeviceType.iPhone-XS-Max)
iPhone Xʀ (com.apple.CoreSimulator.SimDeviceType.iPhone-XR)
iPad mini (5th generation) (com.apple.CoreSimulator.SimDeviceType.iPad-mini--5th-generation-)
iPad Air (3rd generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Air--3rd-generation-)
iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
iPad mini 2 (com.apple.CoreSimulator.SimDeviceType.iPad-mini-2)
iPad mini 3 (com.apple.CoreSimulator.SimDeviceType.iPad-mini-3)
iPad mini 4 (com.apple.CoreSimulator.SimDeviceType.iPad-mini-4)
iPad Air 2 (com.apple.CoreSimulator.SimDeviceType.iPad-Air-2)
iPad (5th generation) (com.apple.CoreSimulator.SimDeviceType.iPad--5th-generation-)
iPad Pro (9.7-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-)
iPad Pro (12.9-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro)
iPad Pro (12.9-inch) (2nd generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---2nd-generation-)
iPad Pro (10.5-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--10-5-inch-)
iPad (6th generation) (com.apple.CoreSimulator.SimDeviceType.iPad--6th-generation-)
iPad Pro (11-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--11-inch-)
iPad Pro (12.9-inch) (3rd generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---3rd-generation-)
Apple TV (com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p)
Apple TV 4K (com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-4K)
Apple TV 4K (at 1080p) (com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-1080p)
Apple Watch - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm)
Apple Watch - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm)
Apple Watch Series 2 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-38mm)
Apple Watch Series 2 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-42mm)
Apple Watch Series 3 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3-38mm)
Apple Watch Series 3 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3-42mm)
Apple Watch Series 4 - 40mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-40mm)
Apple Watch Series 4 - 44mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-44mm)
== Runtimes ==
iOS 11.4 (11.4 - 15F79) - com.apple.CoreSimulator.SimRuntime.iOS-11-4 
iOS 12.4 (12.4 - 16G73) - com.apple.CoreSimulator.SimRuntime.iOS-12-4 
tvOS 12.4 (12.4 - 16M567) - com.apple.CoreSimulator.SimRuntime.tvOS-12-4 
watchOS 5.3 (5.3 - 16U567) - com.apple.CoreSimulator.SimRuntime.watchOS-5-3 
== Devices ==
-- iOS 11.4 --
    iPhone 5s (29152566-A52E-4DC8-8A9F-39F633F146CA) (Shutdown) 
    iPhone 6 (A48BEB2D-782B-42E4-99E5-0AAF8F333F33) (Shutdown) 
    iPhone 6 Plus (AE68F61A-AD30-4D0E-98C4-451164D319A7) (Shutdown) 
    iPhone (34765E48-B6A2-4587-B79E-7A03583C40FA) (Booted) 
    iPhone 6s (**01A1C80D-7DD0-4C7E-88E6-13BBF4B4AEBA**) (Booted) 
    iPhone 6s Plus (E14AD1B4-1EC2-4763-8A23-0E0522E788C4) (Shutdown) 
    iPhone 7 (9EC1B2B1-63AB-4967-9305-49B1E7210B89) (Shutdown) 
    iPhone 7 Plus (2B6B95F7-E1BE-4D86-A909-ABB6F53A5C87) (Shutdown) 
    iPhone 8 (1305635D-0F53-4DED-8F0F-65165FD37DF1) (Shutdown) 
    iPhone 8 Plus (F7A0EA8E-6445-448D-86E0-975237ED9B0C) (Shutdown) 
    iPhone SE (AA47DD0B-B1EA-4264-80CF-DF9EE2157E7D) (Shutdown) 
    iPhone X (FCFF7FA8-0C40-431A-9A8C-9CF34CC84865) (Shutdown) 
    iPad Air (CD958D24-5372-4B3C-BB06-4E1841872D13) (Shutdown) 
    iPad Air 2 (7A53172E-1AAD-476F-9308-8CEE333F2065) (Shutdown) 
    iPad (5th generation) (73ADF088-9C76-4AAD-B704-1756490D1F0E) (Shutdown) 
    iPad Pro (9.7-inch) (09137340-D5E9-4561-B24B-1159C07A42DF) (Shutdown) 
    iPad Pro (12.9-inch) (8BB0661A-4F51-4CBB-BAFA-1F1D6D4D43F5) (Shutdown) 
    iPad Pro (12.9-inch) (2nd generation) (7CE6712B-7B27-42F8-965E-1F1C58C55B4B) (Shutdown) 
    iPad Pro (10.5-inch) (30E4817B-6292-4F82-BBA3-1D3E003BD040) (Shutdown) 
-- iOS 12.4 --

**PFB the ios JSON file details:**

[
  {
    "name": "iPhone",
    "deviceName": "iPhone 6s",
    "platformName": "iOS",
    "platformVersion": "11.4",
    "automationName": "XCuiTest",
    "udid": "01A1C80D-7DD0-4C7E-88E6-13BBF4B4AEBA",
    "reset": true,
    "app": "WordPress.zip"
  }
]

**Comment by srinu-kodi** [comment]
Earlier log says iOS version is 12.4 and Now the list says 11.4.
I am assuming that you have iOS 11.4 version simulators.

As long as you have 11.4 version and UUID 01A1C80D-7DD0-4C7E-88E6-13BBF4B4AEBA, appium will launch the device.

Now after with this 11.4 version simulator info, can you provide me the detailed logs...

The earlier log and device list info is contradicting. So please run and give me the correct logs.

**Comment by ashishp-oyo** [comment]
Detailed logs:

bash-3.2$ java -jar build/libs/Automation-1.0-SNAPSHOT.jar
Nov 28, 2019 8:45:30 PM org.oneframework.logger.LoggingManager logMessage
INFO: Image Comparison arguments not passed; Running tests in functional mode
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Nov 28, 2019 8:45:31 PM org.oneframework.logger.LoggingManager logMessage
INFO: Killing existing appium process
[Appium] Welcome to Appium v1.9.1
[Appium] Non-default server args:
[Appium]   sessionOverride: true
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.9.1"}}
[HTTP] <-- GET /wd/hub/status 200 6 ms - 67
[HTTP] 
Nov 28, 2019 8:45:37 PM org.oneframework.logger.LoggingManager logMessage
INFO: Appium server has been started
Nov 28, 2019 8:45:37 PM org.oneframework.logger.LoggingManager logMessage
INFO: Appium server has been started
Nov 28, 2019 8:45:37 PM org.oneframework.logger.LoggingManager logMessage
INFO: Received the iPhone device configuration for execution
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/Users/ashishpathak/IdeaProjects/OneFramework/WordPress.zip","noReset":true,"platformVersion":"11.4","automationName":"XCuiTest","platformName":"iOS","udid":"01A1C80D-7DD0-4C7E-88E6-13BBF4B4AEBA","deviceName":"iPhone 6s"},"capabilities":{"desiredCapabilities":{"app":"/Users/ashishpathak/IdeaProjects/OneFramework/WordPress.zip","noReset":true,"platformVersion":"11.4","automationName":"XCuiTest","platformName":"iOS","udid":"01A1C80D-7DD0-4C7E-88E6-13BBF4B4AEBA","deviceName":"iPhone 6s"},"firstMatch":[{"appium:app":"/Users/ashishpathak/IdeaProjects/OneFramework/WordPress.zip","appium:automationName":"XCuiTest","appium:deviceName":"iPhone 6s","appium:noReset":true,"platformName":"ios","appium:platformVersion":"11.4","appium:udid":"01A1C80D-7DD0-4C7E-88E6-13BBF4B4AEBA"}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"app":"/Users/ashishpathak/IdeaProjects/OneFramework/WordPress.zip","noReset":true,"platformVersion":"11.4","automationName":"XCuiTest","platformName":"iOS","udid":"01A1C80D-7DD0-4C7E-88E6-13BBF4B4AEBA","deviceName":"iPhone 6s"},null,{"desiredCapabilities":{"app":"/Users/ashishpathak/IdeaProjects/OneFramework/WordPress.zip","noReset":true,"platformVersion":"11.4","automationName":"XCuiTest","platformName":"iOS","udid":"01A1C80D-7DD0-4C7E-88E6-13BBF4B4AEBA","deviceName":"iPhone 6s"},"firstMatch":[{"appium:app":"/Users/ashishpathak/IdeaProjects/OneFramework/WordPress.zip","appium:automationName":"XCuiTest","appium:deviceName":"iPhone 6s","appium:noReset":true,"platformName":"ios","appium:platformVersion":"11.4","appium:udid":"01A1C80D-7DD0-4C7E-88E6-13BBF4B4AEBA"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1574954138188 (20:45:38 GMT+0530 (India Standard Time))
[Appium] Creating new XCUITestDriver (v2.94.2) session
[Appium] Capabilities:
[Appium]   platformName: ios
[Appium]   app: /Users/ashishpathak/IdeaProjects/OneFramework/WordPress.zip
[Appium]   automationName: XCuiTest
[Appium]   deviceName: iPhone 6s
[Appium]   noReset: true
[Appium]   platformVersion: 11.4
[Appium]   udid: 01A1C80D-7DD0-4C7E-88E6-13BBF4B4AEBA
[debug] [BaseDriver] W3C capabilities {"alwaysMatch":{"platformNa... and MJSONWP desired capabilities {"app":"/Users/ashishpathak... were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Session created with session id: 71c7589c-459b-4a1b-b939-33f1354e743d
(node:9174) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[debug] [XCUITest] Current user: 'ashishpathak'
[debug] [XCUITest] Xcode version set to '10.3' (tools v10.3.0.0.1.1562985497)
[debug] [XCUITest] iOS SDK Version set to '12.4'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1574954138601 (20:45:38 GMT+0530 (India Standard Time))
[debug] [XCUITest] Available devices: 
[XCUITest] Error: Unknown device or simulator UDID: '01A1C80D-7DD0-4C7E-88E6-13BBF4B4AEBA'
[XCUITest]     at XCUITestDriver.determineDevice$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:693:17)
[XCUITest]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[XCUITest]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[XCUITest]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[XCUITest]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1574954140667 (20:45:40 GMT+0530 (India Standard Time))
[debug] [W3C] Encountered internal error running command: Error: Unknown device or simulator UDID: '01A1C80D-7DD0-4C7E-88E6-13BBF4B4AEBA'
[debug] [W3C]     at XCUITestDriver.determineDevice$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:693:17)
[debug] [W3C]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[debug] [W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[debug] [W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[debug] [W3C]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 2498 ms - 1207
[HTTP] 
TEST SKIP: testSignInOption - testing the signin page visually
TEST SKIP: testSignUpOption - testing the signup page visually
Nov 28, 2019 8:45:55 PM org.oneframework.logger.LoggingManager logMessage
INFO: Appium server has been stopped
Nov 28, 2019 8:45:55 PM org.oneframework.logger.LoggingManager logMessage
INFO: Appium server has been stopped
TEST FINISH: E2E Test Suite On iOS - iPhone6S

**Comment by srinu-kodi** [comment]
Hi Ashish,
I do not think there is any issue with the framework. But looks like backward compatibility issue..

Looking at the log, below 2 lines
[debug] [W3C] at XCUITestDriver.determineDevice$ (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:693:17)
[debug] [W3C] at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)

It appears that there is a issue with appium-xcuitest-driver. When I have created this framework, I took appium 1.11.1 version appium npm module. Can you please check by installing the appium 1.11.1 version. I hope it solves. xcuitest test looks like not compatible with 1.9.1 version appium...

**Comment by ashishp-oyo** [comment]
After changing the appium version to 1.11.1, I am able to start the simulator but unable to start to launch webdriveragent. PFB the logs:
[debug] [XCUITest] Killing running processes 'xcodebuild.*01A1C80D-7DD0-4C7E-88E6-13BBF4B4AEBA, iproxy 8100, 01A1C80D-7DD0-4C7E-88E6-13BBF4B4AEBA.*XCTRunner' for the device 01A1C80D-7DD0-4C7E-88E6-13BBF4B4AEBA...
[debug] [XCUITest] 'pgrep -nif xcodebuild.*01A1C80D-7DD0-4C7E-88E6-13BBF4B4AEBA' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif 01A1C80D-7DD0-4C7E-88E6-13BBF4B4AEBA.*XCTRunner' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=01A1C80D-7DD0-4C7E-88E6-13BBF4B4AEBA IPHONEOS_DEPLOYMENT_TARGET=11.4' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged. To change this, use 'showXcodeLog' desired capability
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[WD Proxy] Got an unexpected response: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8100}
[debug] [XCUITest] Log file for xcodebuild test: /Users/ashishpathak/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Test-WebDriverAgentRunner-2019.11.29_13-43-04-+0530.xcresult/2_Test/Diagnostics/WebDriverAgentRunner-D7ABC872-50A2-43C1-B154-9686B07F0C37/WebDriverAgentRunner-5E7413D0-B93C-45C0-83A9-90D4208A0810/Session-WebDriverAgentRunner-2019-11-29_134308-vjAznW.log
[Xcode] 2019-11-29 13:43:08.290 xcodebuild[16415:5343441] Error Domain=IDETestApplcationDependencyMapperErrorDomain Code=2 "The bundle identifier for WebDriverAgentRunner-Runner.app couldn’t be read." UserInfo={NSLocalizedFailureReason=The application may be damaged or incomplete: “/Users/ashishpathak/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app”., NSURL=file:///Users/ashishpathak/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/, NSFilePath=/Users/ashishpathak/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app, NSLocalizedDescription=The bundle identifier for WebDriverAgentRunner-Runner.app couldn’t be read.}
[Xcode] 
[Xcode] 
[Xcode] Testing failed:
[Xcode] 
[Xcode] 	Messaging unqualified id
[Xcode] 	Messaging unqualified id
[Xcode] 
[Xcode] Test session results and logs:
[Xcode] 	/Users/ashishpathak/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Test-WebDriverAgentRunner-2019.11.29_13-43-04-+0530.xcresult
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] Testing started on 'iPhone 6s'

**Comment by srinu-kodi** [comment]
Hi Ashish,
If you  see the logs, it says that there is an issue with WebDriverAgentRunner which is either corrupted or not built properly before it is launched. Can you please delete the WebDriverAgentRunner.app in the path and re-run the tests, it should be fine....

It is not OneFramework issue. However if you need help in fixing this, please create a simple repo and send it to me. I will take a look at it.

**Comment by srinu-kodi** [comment]
Due to inactivity of this, Closing this issue, since it is not a OneFramework issue. If it is still persists, provide me the logs and all the details and follow the step that have been mentioned above....
